Pandas - Everything in Pandas

In [18]:
import pandas as pd 
#dates = pd.date_range("20231025", periods=6)
df = pd.read_csv('bmi.csv')
#df.sort_values(by='Age')
#df.sort_index(axis=1 , ascending=False)
#df.loc[:50 , "Weight"]
#df.iloc[:50 , 4]
#df[df['Age'].isin([15, 42])]
#df.dropna(), fillna() , 
#pd.isna(df)
#df.mean(axis=1)
#df.agg(), .transform()
#.value_counts()
#pd.concat()
#pd.merge(a, b, on="key")
#df.groupby("BmiClass")["Age"].mean()
#pivot_table

In [25]:
#.fillna()
#df.isnull().sum()
'''df.dropna(
    axis=0,         # Whether to drop rows or columns
    how='any',      # Whether to drop records if 'all' or 'any' records are missing
    thresh=None,    # How many columns/rows must be missing to drop
    subset=None,    # Which rows/columns to consider
    inplace=False   # Whether to drop in place (i.e., without needing to re-assign)
)'''
#df.fillna(0)
#df.duplicated()
#df.drop_duplicates()
#df['Flower'].str.strip()  #To clean white spaces
#df['Region'].str.replace('Region ', '')
#df.upper(),lower(),title()
#df[df.Bmi > 32]
#df.sample(frac=0.01)
#df.nlargest(5 , 'Bmi')
#df.nsmallest(5 , 'Bmi')
#df.query('Bmi > 30')
#df.query('Bmi > 30 and Age < 60')
#df.shape
#df['Age'].nunique()
#df.groupby(by="Age").size()
#df.groupby(by="Age").rank(method='dense')

     Height  Weight   Bmi  BmiClass
0       1.0     1.0   1.0       1.0
1       4.0     3.0   2.0       3.0
2       2.0     2.0   3.0       1.0
3       1.0     1.0   1.0       4.0
4       3.0     4.0   4.0       2.0
..      ...     ...   ...       ...
736    15.0    15.0  16.0       4.0
737    13.0    11.0  10.0       4.0
738    16.0    20.0  22.0       5.0
739    14.0    15.0  14.0       4.0
740    13.0    10.0  10.0       4.0

[741 rows x 4 columns]